version: '3'

services:
  db:
    image: postgres:16-alpine
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 3001:5432
    environment:
      POSTGRES_DB: 4gaBoards
      POSTGRES_PASSWORD: abb2d609bc3fa0c10f1126d849c4a023c1ec67f3a3984bf3db21027dd6cd58e215ef0bdda042ed0e413d492bc2897043af00128dbfa52adc74a9bef9df8c1c0d
      POSTGRES_INITDB_ARGS: "-A scram-sha-256"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d 4gaBoards"]
      interval: 5s
      timeout: 5s
      retries: 10

  4gaBoards:
    image: ghcr.io/rargames/4gaboards:latest
    restart: always
    volumes:
      - user-avatars:/app/public/user-avatars
      - project-background-images:/app/public/project-background-images
      - attachments:/app/private/attachments
    ports:
      - 3000:1337
    environment:
      BASE_URL: http://alcu1n.com:3000
      SECRET_KEY: abb2d609bc3fa0c10f1126d849c4a023c1ec67f3a3984bf3db21027dd6cd58e215ef0bdda042ed0e413d492bc2897043af00128dbfa52adc74a9bef9df8c1c0d
      DATABASE_URL: postgresql://postgres:abb2d609bc3fa0c10f1126d849c4a023c1ec67f3a3984bf3db21027dd6cd58e215ef0bdda042ed0e413d492bc2897043af00128dbfa52adc74a9bef9df8c1c0d@db/4gaBoards
      NODE_ENV: production
    depends_on:
      db:
        condition: service_healthy

volumes:
  user-avatars:
  project-background-images:
  attachments:
  db-data:
