version: '3'

services:
  4gaBoards:
    image: ghcr.io/rargames/4gaboards:latest
    command: >
      bash -c
        "for i in `seq 1 30`; do
          ./start.sh &&
          s=$$? && break || s=$$?;
          echo \"Tried $$i times. Waiting 5 seconds...\";
          sleep 5;
        done; (exit $$s)"
    restart: always
    volumes:
      - user-avatars:/app/public/user-avatars
      - project-background-images:/app/public/project-background-images
      - attachments:/app/private/attachments
    ports:
      - 3000:1337
    environment:
      - BASE_URL=http://localhost:3000
      - SECRET_KEY=notsecretkey
      - DATABASE_URL=postgresql://postgres@postgres/4gaBoards
      - TRUST_PROXY=0
    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5000:5432
    environment:
      - POSTGRES_DB=4gaBoards
      - POSTGRES_HOST_AUTH_METHOD=trust

volumes:
  user-avatars:
  project-background-images:
  attachments:
  db-data:
